// app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { CSPostHogProvider } from './providers'; // Path is correct if providers.tsx is in the app dir
import Script from 'next/script';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        {/* Add the Video Player CSS here */}
        <link
          href='https://unpkg.com/cloudinary-video-player@1.9.4/dist/cld-video-player.min.css'
          rel='stylesheet'
        />
      </head>
      <body className={inter.className}>
        <CSPostHogProvider>{children}</CSPostHogProvider>
      </body>
      <Script
        src='https://unpkg.com/cloudinary-video-player@1.9.4/dist/cld-video-player.min.js'
        strategy='afterInteractive' // Loads the script after the page is interactive
      />
    </html>
  );
}
